# Generated by Django 3.1.3 on 2020-11-09 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('nome', models.CharField(max_length=100)),
                ('cargo', models.IntegerField(choices=[(1, 'Prefeito')])),
                ('numero', models.IntegerField()),
                ('partido', models.CharField(max_length=8)),
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=100)),
                ('doc', models.CharField(max_length=100, unique=True)),
                ('doc_raiz', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('doc', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sociedade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_socio', models.CharField(max_length=100)),
                ('qualificacao_socio', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receitas.empresa')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receitas.pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_originario', models.CharField(max_length=16, null=True)),
                ('nome_doador_originario', models.CharField(max_length=100, null=True)),
                ('data', models.DateField()),
                ('especia_do_recurso', models.CharField(max_length=100)),
                ('descricao_do_recurso', models.CharField(max_length=200, null=True, verbose_name='Descrição do recurso')),
                ('numero_documento', models.CharField(max_length=22, null=True)),
                ('recibo_eleitoral', models.CharField(max_length=22, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor (R$)')),
                ('fonte', models.CharField(max_length=100)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receitas.candidato', verbose_name='Candidato')),
                ('pessoa_doador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receitas.pessoa', verbose_name='Doador')),
            ],
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_fornecedor', models.CharField(max_length=16)),
                ('nome_fornecedor', models.CharField(max_length=100, null=True, verbose_name='Fornecedor')),
                ('doc_doador_originario', models.CharField(max_length=16, null=True)),
                ('nome_doador_originario', models.CharField(max_length=100, null=True)),
                ('data', models.DateField()),
                ('especia_do_recurso', models.CharField(max_length=100)),
                ('numero_documento', models.CharField(max_length=22, null=True)),
                ('recibo_eleitoral', models.CharField(max_length=22, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Valor (R$)')),
                ('candidato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='receitas.candidato', verbose_name='Candidato')),
            ],
        ),
    ]
