# Generated by Django 3.1.3 on 2020-11-09 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=100)),
                ('doc', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('doc', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='receita',
            name='doc',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='nome_doador',
        ),
        migrations.AlterField(
            model_name='despesa',
            name='candidato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='receitas.candidato', verbose_name='Candidato'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='nome_fornecedor',
            field=models.CharField(max_length=100, null=True, verbose_name='Fornecedor'),
        ),
        migrations.AlterField(
            model_name='receita',
            name='candidato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receitas.candidato', verbose_name='Candidato'),
        ),
        migrations.CreateModel(
            name='Sociedade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_socio', models.CharField(max_length=100)),
                ('qualificacao_socio', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receitas.empresa')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receitas.pessoa')),
            ],
        ),
        migrations.AddField(
            model_name='receita',
            name='pessoa_doador',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='receitas.pessoa'),
            preserve_default=False,
        ),
    ]
