# Generated by Django 3.1.3 on 2020-11-09 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_auto_20201109_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='numero_documento',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='recibo_eleitoral',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
