# Generated by Django 3.1.3 on 2020-11-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_auto_20201108_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='doc_raiz',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
